### ISSUE TITLE
Bug: Resize hero section button for smaller sizes.

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#353]
### Describe the bug.

The button size looks bigger wrt to the section layout for max-width: 460px

### Expected behavior.

Ideally, it should look how it looks at 363 px.

### Screenshots.

<img width="1440" alt="Screenshot 2022-08-21 at 11 50 50 PM" src="https://user-images.githubusercontent.com/75530516/185805674-bf8285a0-5979-47f8-bb1b-b2a46f8efcf6.png">

### Operating Environment

macOS 12.5

**Comment by Vedant-Manjrekar** [comment]
Hi @padmajabhol, is this issue solved because right now the page looks like this:

<img width="1055" alt="Screenshot 2022-08-22 at 11 18 43 AM" src="https://user-images.githubusercontent.com/93585735/185848385-106e4a60-235a-4eb9-a4c4-c6938cb30743.png">

The button size on width 363px is also similar to that of width 460px. So what changes are you exactly expecting.

Am I comprehending the issue correctly or am I missing out on something?

**Comment by prerana1821** [comment]
Hey, I would like to work on this

**Comment by padmajabhol** [comment]
> Hi @padmajabhol, is this issue solved because right now the page looks like this:
> 
> <img alt="Screenshot 2022-08-22 at 11 18 43 AM" width="1055" src="https://user-images.githubusercontent.com/93585735/185848385-106e4a60-235a-4eb9-a4c4-c6938cb30743.png">
> 
> The button size on width 363px is also similar to that of width 460px. So what changes are you exactly expecting.
> 
> Am I comprehending the issue correctly or am I missing out on something?

Hi, you need to change to https://github.com/moja-global/community-website/tree/community-website.v2 branch before you can see the issue.

**Comment by 03amir** [comment]
@padmajabhol  is this issue solved? or can i take this?

**Comment by ComradeCat24** [comment]
Hey, Could you assign me this task? 
I would like to work on this
