### ISSUE TITLE
Navbar Logo fix for Dark-Theme

### ISSUE THREAD

**Issue by Siddhant-K-code** [moja-global/community-website#48]
Though our Logo looks good in light-theme, it looks a bit off in Dark-theme. Background Color cover's our logo text. 
Light-Theme: 

![image](https://user-images.githubusercontent.com/55068936/128302030-6034b31b-d4b1-4304-bfae-54d1cdfdcef1.png)
 
Dark-Theme:

![image](https://user-images.githubusercontent.com/55068936/128302079-ac42dbbf-5e25-4912-b896-f1e5ef2e4c58.png)

Possible Solution: We can use one with white text as we have in GitHub Organisation Picture. Or Just Create Another Same logo with White text.

**Comment by aornugent** [comment]
See https://github.com/moja-global/About_moja_global/issues/137 for brand assets.

Can we match the dark green logo for dark theme?

![Uploading Logos_1000x1000pxLogo-w-icon-1.png…]()

**Comment by Siddhant-K-code** [comment]
We Can use the transparent version of this.

**Comment by Siddhant-K-code** [comment]
We Can use [this](https://github.com/moja-global/community-website/blob/main/website/static/img/logo-light.png)

**Comment by aornugent** [comment]
Apologies - I didn't realise our brand assets were restricted. I don't have the permissions to share the folder.

@sarthakkundra - let's finish https://github.com/moja-global/About_moja_global/issues/137 so that we can link to the governance docs as a way to share our logos and imagery. This only requires updating the assets in the docs to the new content.
