### ISSUE TITLE
Create Github Action

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/community-website#8]
An initial Github action should do the following things :- 

- [ ] Greet first time contributors.

**Comment by d-cryptic** [comment]
Is this issue still open?

**Comment by toth2000** [comment]
I would like to work on this issue.

**Comment by Jassi10000** [comment]
@HarshCasper Can I work on this issue , Please assign me

**Comment by sarthakkundra** [comment]
Assigned @Jassi10000. Let me know if you need anything :)

**Comment by Jassi10000** [comment]
Sure , thank you @sarthakkundra

**Comment by HarshCasper** [comment]
Hi @Jassi10000 

We already have added a lot of actions here. We would appreciate help with this: https://github.com/moja-global/community-website/blob/main/.github/workflows/build-size.yml

Currently, the Build Size bot doesn't work properly. It might be due to the `package-lock.json` being polluted by broken deps. Here is how you can test it out and resolve the same: 

- Fork the repo and enable actions workflow on the same
- Make a dummy PR and check the bug on the Actions tab
- Fix the deps locally and push the changes to see if the Build Bot is back again.
- Make a PR once you are satisfied with your changes.

**Comment by Jassi10000** [comment]
Btw am nearly completed with first time contributors action , should i leave it or send a PR for that too ?
